### ISSUE TITLE
Serve React app from subdirectory

### ISSUE THREAD

**Issue by KGmajor** [YearOne-Prep/YearOne-prep-challenges#9]
I'd like to use the information from the topics yaml to serve on a static React site. In order to access the yaml, the React application should live in a subdirectory and access the same yaml as the posts that go to the community. 

**Describe the solution you'd like**
Use create react app, but keep the react files serving from a subdirectory named `react`. 

**Additional context**
We'll probably use a tool like render to deploy the static page.

**Comment by frostzt** [comment]
Hey, rather than using React only how about Nextjs? Will that be good?
